sudo: required
Services:
    - docker
    
before_install:
    - docker build -t viveksingha/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true viveksingha/docker-react npm run test
    
language: generic

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-044139717698"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"