sudo: required
Services:
    - docker
    
before_install:
    - docker build -t viveksingha/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true viveksingha/docker-react npm run test
    
language: generic